#!/bin/bash
# Generate Kubernetes manifests for TP2, TP4, TP8 configurations
# Usage: ./generate-manifests.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
K8S_DIR="$PROJECT_ROOT/deploy/k8s"

# Source environment for defaults
if [[ -f "$PROJECT_ROOT/deploy/aws/env.sh" ]]; then
    source "$PROJECT_ROOT/deploy/aws/env.sh"
fi

echo "Generating Kubernetes manifests..."

# Generate manifest for each TP configuration
for TP_SIZE in 2 4 8; do
    MANIFEST="$K8S_DIR/mini-vllm-tp${TP_SIZE}.yaml"
    DEPLOYMENT_NAME="${MINI_VLLM_PREFIX:-mini-vllm-}gptoss-tp${TP_SIZE}"
    
    echo "  Creating $MANIFEST"
    
    cat > "$MANIFEST" << 'YAML_EOF'
# Mini-vLLM Deployment - Tensor Parallel ${TP_SIZE}
# Generated by generate-manifests.sh
#
# Deploy: kubectl apply -f mini-vllm-tp${TP_SIZE}.yaml -n hyperpod-ns-inference
# Delete: kubectl delete -f mini-vllm-tp${TP_SIZE}.yaml -n hyperpod-ns-inference

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
  namespace: ${MINI_VLLM_NAMESPACE}
  labels:
    app: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
    kueue.x-k8s.io/queue-name: "${MINI_VLLM_KUEUE_QUEUE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
  template:
    metadata:
      labels:
        app: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
        kueue.x-k8s.io/queue-name: "${MINI_VLLM_KUEUE_QUEUE}"
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: ${MINI_VLLM_NODE_TYPE}
      containers:
      - name: mini-vllm
        image: ${MINI_VLLM_REGISTRY}/${MINI_VLLM_PREFIX}server:latest
        imagePullPolicy: Always
        args:
        - --model
        - ${MINI_VLLM_MODEL_PATH}
        - --tensor-parallel-size
        - "${TP_SIZE}"
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        - --dtype
        - "bfloat16"
        ports:
        - containerPort: 8000
          name: http
        env:
        # CUDA settings
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1,2,3,4,5,6,7"
        # NCCL optimization for H100
        - name: NCCL_DEBUG
          value: "WARN"
        - name: NCCL_IB_DISABLE
          value: "0"
        - name: NCCL_NET_GDR_LEVEL
          value: "2"
        # Memory optimization
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: "expandable_segments:True"
        volumeMounts:
        - name: fsx-models
          mountPath: /mnt/fsx
        - name: shm
          mountPath: /dev/shm
        resources:
          requests:
            nvidia.com/gpu: ${TP_SIZE}
            memory: "64Gi"
            cpu: "8"
          limits:
            nvidia.com/gpu: ${TP_SIZE}
            memory: "128Gi"
            cpu: "16"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: fsx-models
        persistentVolumeClaim:
          claimName: ${MINI_VLLM_FSX_PVC}
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
  namespace: ${MINI_VLLM_NAMESPACE}
spec:
  selector:
    app: ${MINI_VLLM_PREFIX}gptoss-tp${TP_SIZE}
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
YAML_EOF

    # Replace variables in the generated file
    sed -i "s/\${TP_SIZE}/${TP_SIZE}/g" "$MANIFEST"
    
done

echo ""
echo "Generated manifests:"
ls -la "$K8S_DIR"/*.yaml

echo ""
echo "Next steps:"
echo "  1. Update deploy/aws/credentials.sh with your AWS credentials"
echo "  2. Run: source deploy/aws/env.sh"
echo "  3. Run: ./deploy/scripts/setup-ecr.sh"
echo "  4. Run: ./deploy/scripts/build.sh"
echo "  5. Run: ./deploy/scripts/deploy.sh tp2"

